# SwiftLint configuration for BudgetTracker
# See: https://github.com/realm/SwiftLint

# Opt in to additional rules that are generally helpful for SwiftUI/SwiftData apps
opt_in_rules:
  - anyobject_protocol
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - empty_count
  - empty_xctest_method
  - expiring_todo
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nslocalizedstring_require_bundle
  - number_separator
  - optional_enum_case_matching
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - yoda_condition

# Disabled rules (project preferences)
disabled_rules:
  - line_length
  - todo

# Included paths (defaults to all swift files)
# You can add more folders here if needed
included:
  - BudgetTracker

# Excluded paths
excluded:
  - Pods
  - .build
  - DerivedData
  - fastlane
  - Scripts
  - Package.resolved

# Customizable rules
identifier_name:
  min_length: 2
  excluded: [id, x, y, i, j]

type_name:
  min_length: 3

file_length:
  warning: 600
  error: 1200

function_body_length:
  warning: 60
  error: 100

cyclomatic_complexity:
  warning: 12
  error: 20

nesting:
  type_level:
    warning: 3

force_cast:
  severity: warning

force_try:
  severity: warning

implicit_return:
  included: [closure, function]

trailing_comma:
  mandatory_comma: true

unused_declaration:
  severity: warning

unused_import:
  severity: warning

# Enforce a simple file header to keep files consistent
file_header:
  required_pattern: "^//\\n//  .+\\n//  BudgetTracker\\n//\\n//  Created by .+ on .+\\n//\\n$"

# Reporter
reporter: xcode
